// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/ninedraft/bibliotheca/storage/ent/book"
	"github.com/ninedraft/bibliotheca/storage/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bookFields := schema.Book{}.Fields()
	_ = bookFields
	// bookDescWrittenAt is the schema descriptor for written_at field.
	bookDescWrittenAt := bookFields[2].Descriptor()
	// book.DefaultWrittenAt holds the default value on creation for the written_at field.
	book.DefaultWrittenAt = bookDescWrittenAt.Default.(func() int64)
}
